version: 1.0.{build}
os: Visual Studio 2015 CTP
configuration: Release

environment:
  ZipPackageCompressionLevel: normal
  DeployExtension: false

install: 
  - ps: Start-FileDownload https://raw.githubusercontent.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1
  - ps: Import-Module './vsix.ps1'

before_build: 
  - ps: Vsix-IncrementVsixVersion -updateBuildVersion
  - nuget.exe restore

build:
  verbosity: minimal
  project: WebEssentials2015.sln

after_test:
  - ps: Vsix-PushArtifacts -publishToGallery